### ISSUE TITLE
디자인하기

### ISSUE THREAD

**Issue by MiryangJung** [EveryAnalytics-Study/todo-list#2]
`emotion` 을 사용하여 해봅시다!

- https://github.com/EveryAnalytics/web-analytics-handbook/pull/13

디자인 레퍼런스
- https://todomvc.com/examples/typescript-react/#/
- https://codepen.io/shshaw/pen/WXMdwE
- https://codepen.io/saawsan/pen/jayzeq

**Comment by sensecodevalue** [comment]
제가 해보겠습니다! 열열정정!

**Comment by MiryangJung** [comment]
디자인레퍼런스 조금 추가해뒀습니다~ 화이팅!
